### ISSUE TITLE
Null Pointer when calling handle.click()

### ISSUE THREAD

**Issue by CrepeClown** [uchagani/allure-playwright-java#5]
I appear to have everything configured properly and am able to execute the tests with your dependency commented out. However, when trying to use your library I receive the following error.

Is this a lack of functionality when working with handles directly?

Relevant code:

public DemographicsPage selectGender(String gender){
        for(ElementHandle handle : page.querySelectorAll("[name="+rdoGender+"]")){
            if(handle.getAttribute("value").equalsIgnoreCase(gender)){
                handle.click();
            }
        }
        return this;
    }

java.lang.NullPointerException
	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.getStepNameForLocator(ChannelOwnerAspect.java:118)
	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.getStepName(ChannelOwnerAspect.java:191)
	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.beforeActionMethods(ChannelOwnerAspect.java:79)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.ElementHandleImpl.clickImpl(ElementHandleImpl.java:143)
	at com.microsoft.playwright.impl.ElementHandleImpl.lambda$click$6(ElementHandleImpl.java:135)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.ElementHandleImpl.click(ElementHandleImpl.java:135)
	at com.microsoft.playwright.ElementHandle.click(ElementHandle.java:1288)
	at pages.patientaccesspages.DemographicsPage.selectGender(DemographicsPage.java:39)
	at PASAdmitTests.verifyA01MessageSentWhenNewAdmitEncAdded(PASAdmitTests.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

**Comment by uchagani** [comment]
thanks for reporting this, i didn't consider handles since playwright discourages their use.  however, i will look to see how to fix this.

**Comment by CrepeClown** [comment]
Thanks for getting back to me so soon. I am fairly new to Playwright and was not aware this was frowned upon.

Out of curiosity, is there a solution you would recommend for the above scenario? In the above we are taking the test input for gender and since all buttons share the same name, matching the correct value to that element.

This was done to bypass creating separate functions for each gender button. If there is a better way of doing this I would love to know.

**Comment by uchagani** [comment]
no worries, you should use locators instead of handles.

so in your case you can do something like:

```java
Locator genders = page.locator("[name="+rdoGender+"]");

for(int i = 0; i < genders.count(); i++) {
  Locator g = genders.nth(i);
  if(g.getAttribute("value").equalsIgnoreCase(gender)) {
    g.click();
  }   
}
```

**Comment by CrepeClown** [comment]
Thanks so much! That got everything working. I will leave the issue open if you feel you want to add that functionality.
